/* Basketball coaching English - curated content (ES ⇆ EN)
   Pronunciation guide ("say") is a Spanish-friendly respelling, not IPA,
   so a Spanish speaker can read it aloud and be understood.
   Stress is marked with CAPS on the stressed syllable. */

export default {
  categories: [
    {
      id: 'positions',
      es: 'Posiciones y roles',
      en: 'Positions & roles',
      glyph: 'pos',
      terms: [
        { en: 'Point guard',     es: 'Base (1)',            say: 'póint gard',      note: 'Dirige el ataque.' },
        { en: 'Shooting guard',  es: 'Escolta (2)',         say: 'shú-tin gard' },
        { en: 'Small forward',   es: 'Alero (3)',           say: 'smol fór-uard' },
        { en: 'Power forward',   es: 'Ala-pívot (4)',       say: 'páuer fór-uard' },
        { en: 'Center',          es: 'Pívot (5)',           say: 'SÉN-ter' },
        { en: 'Ball handler',    es: 'Manejador del balón', say: 'bol HÁND-ler' },
        { en: 'Wing',            es: 'Exterior / alero',    say: 'uíng' },
        { en: 'Post player',     es: 'Jugador interior',    say: 'póust PLÉI-er' },
        { en: 'Trailer',         es: 'Jugador que llega por detrás', say: 'TRÉI-ler' },
        { en: 'Sixth man',       es: 'Sexto hombre',        say: 'siksz man' },
      ],
    },
    {
      id: 'offense',
      es: 'Ataque y jugadas',
      en: 'Offense & plays',
      glyph: 'off',
      terms: [
        { en: 'Pick and roll',   es: 'Bloqueo y continuación', say: 'pik and roul', note: 'El bloqueador rueda al aro.' },
        { en: 'Pick and pop',    es: 'Bloqueo y abrirse a tirar', say: 'pik and pop' },
        { en: 'Screen',          es: 'Bloqueo (pantalla)',  say: 'skríin' },
        { en: 'Set a screen',    es: 'Poner un bloqueo',    say: 'set a skríin' },
        { en: 'Off-ball screen', es: 'Bloqueo sin balón',   say: 'of-bol skríin' },
        { en: 'Cut',             es: 'Corte',               say: 'cot' },
        { en: 'Backdoor cut',    es: 'Puerta atrás',        say: 'BÁK-dor cot' },
        { en: 'Give and go',     es: 'Pasa y va',           say: 'guiv and góu' },
        { en: 'Hand-off',        es: 'Entrega de mano',     say: 'HÁND-of' },
        { en: 'Drive',           es: 'Penetración',         say: 'dráiv' },
        { en: 'Kick-out',        es: 'Pase de descarga',    say: 'kik-áut' },
        { en: 'Spacing',         es: 'Espaciado / abrir la pista', say: 'SPÉI-sin' },
        { en: 'Isolation (iso)', es: 'Uno contra uno',      say: 'ai-so-LÉI-shon' },
        { en: 'Post up',         es: 'Jugar de espaldas',   say: 'póust op' },
        { en: 'Fast break',      es: 'Contraataque',        say: 'fast bréik' },
        { en: 'Transition',      es: 'Transición',          say: 'tran-SÍ-shon' },
      ],
    },
    {
      id: 'defense',
      es: 'Defensa',
      en: 'Defense',
      glyph: 'def',
      terms: [
        { en: 'Man-to-man',      es: 'Defensa individual',  say: 'man-tu-man' },
        { en: 'Zone defense',    es: 'Defensa en zona',     say: 'zóun de-FENS' },
        { en: 'Help defense',    es: 'Defensa de ayuda',    say: 'help de-FENS' },
        { en: 'Close out',       es: 'Basculación / cerrar al tirador', say: 'klóus-áut', note: 'Salir controlado al tirador.' },
        { en: 'Box out',         es: 'Bloqueo de rebote',   say: 'boks áut' },
        { en: 'Switch',          es: 'Cambio',              say: 'suích' },
        { en: 'Hedge',           es: 'Mostrar / salir al bloqueo', say: 'hech' },
        { en: 'Drop coverage',   es: 'Cobertura atrás (drop)', say: 'drop CÓ-ve-rich' },
        { en: 'Deny',            es: 'Negar la línea de pase', say: 'di-NÁI' },
        { en: 'Contest the shot',es: 'Disputar el tiro',    say: 'con-TEST de shot' },
        { en: 'Trap',            es: 'Trampa / 2 contra 1', say: 'trap' },
        { en: 'Rotate',          es: 'Rotar',               say: 'RÓU-teit' },
        { en: 'Stance',          es: 'Posición defensiva',  say: 'stans' },
      ],
    },
    {
      id: 'court',
      es: 'Pista y material',
      en: 'Court & equipment',
      glyph: 'court',
      terms: [
        { en: 'Hoop / rim',      es: 'Aro',                 say: 'húup / rim' },
        { en: 'Backboard',       es: 'Tablero',             say: 'BÁK-bord' },
        { en: 'Net',             es: 'Red',                 say: 'net' },
        { en: 'The paint / key', es: 'La zona',             say: 'de péint / kíi' },
        { en: 'Free-throw line', es: 'Línea de tiros libres', say: 'fríi-zróu láin' },
        { en: 'Three-point line',es: 'Línea de tres',       say: 'zríi-póint láin' },
        { en: 'Baseline',        es: 'Línea de fondo',      say: 'BÉIS-lain' },
        { en: 'Sideline',        es: 'Línea de banda',      say: 'SÁID-lain' },
        { en: 'Half court',      es: 'Medio campo',         say: 'haf cort' },
        { en: 'Elbow',           es: 'El codo (de la zona)', say: 'ÉL-bou' },
        { en: 'Top of the key',  es: 'Frontal',             say: 'top of de kíi' },
        { en: 'The wing',        es: 'El ala (45º)',        say: 'de uíng' },
        { en: 'The block',       es: 'El poste bajo',       say: 'de blok' },
        { en: 'Cone',            es: 'Cono',                say: 'kóun' },
        { en: 'Whistle',         es: 'Silbato',             say: 'UÍ-sel' },
        { en: 'Scrimmage',       es: 'Partidillo',          say: 'SKRÍ-mich' },
      ],
    },
    {
      id: 'body',
      es: 'Cuerpo y movimiento',
      en: 'Body & movement',
      glyph: 'body',
      terms: [
        { en: 'Dribble',         es: 'Botar',               say: 'DRÍ-bol' },
        { en: 'Pass',            es: 'Pasar',               say: 'pas' },
        { en: 'Shoot',           es: 'Tirar',               say: 'shúut' },
        { en: 'Catch',           es: 'Recibir / atrapar',   say: 'kach' },
        { en: 'Pivot',           es: 'Pivotar',             say: 'PÍ-vot' },
        { en: 'Square up',       es: 'Encarar el aro',      say: 'skuéar op' },
        { en: 'Get low',         es: 'Baja el centro de gravedad', say: 'guet lóu' },
        { en: 'Move your feet',  es: 'Mueve los pies',      say: 'múuv yor fíit' },
        { en: 'Stay on your toes',es:'Mantente sobre las puntas', say: 'stéi on yor tóus' },
        { en: 'Hands up',        es: 'Manos arriba',        say: 'hands op' },
        { en: 'Wide stance',     es: 'Postura ancha',       say: 'uáid stans' },
        { en: 'Sprint',          es: 'Esprintar',           say: 'sprint' },
        { en: 'Jog',             es: 'Trotar',              say: 'chog' },
        { en: 'Slide',           es: 'Deslizarse (defensa)', say: 'sláid' },
      ],
    },
    {
      id: 'cues',
      es: 'Ánimo y correcciones',
      en: 'Encouragement & cues',
      glyph: 'cues',
      terms: [
        { en: 'Good job!',       es: '¡Buen trabajo!',      say: 'gud chob' },
        { en: 'Nice!',           es: '¡Bien!',              say: 'náis' },
        { en: 'One more!',       es: '¡Una más!',           say: 'uán mor' },
        { en: 'Again!',          es: '¡Otra vez!',          say: 'a-GUÉN' },
        { en: "Let's go!",       es: '¡Vamos!',             say: 'lets góu' },
        { en: 'Reset!',          es: '¡De nuevo desde el principio!', say: 'ri-SET' },
        { en: 'Talk!',           es: '¡Hablad / comunicad!', say: 'tok' },
        { en: 'Hustle!',         es: '¡A tope, con intensidad!', say: 'HÓ-sel' },
        { en: 'Lock in!',        es: '¡Concentración!',     say: 'lok in' },
        { en: 'Push the pace!',  es: '¡Subid el ritmo!',    say: 'push de péis' },
        { en: 'Slow it down',    es: 'Bajad el ritmo',      say: 'slóu it dáun' },
        { en: 'Way to go!',      es: '¡Así se hace!',       say: 'uéi tu góu' },
        { en: 'Eyes up!',        es: '¡Cabeza arriba!',     say: 'áis op' },
        { en: 'Finish strong!',  es: '¡Termina fuerte!',    say: 'FÍ-nish strong' },
      ],
    },
  ],

  phraseGroups: [
    {
      es: 'Para organizar al grupo',
      en: 'Organising the group',
      items: [
        { en: 'Bring it in!',           es: '¡Todos aquí! (piña)', say: 'bring it in' },
        { en: 'Partner up.',            es: 'Por parejas.',        say: 'PÁRT-ner op' },
        { en: 'Get into groups of three.', es: 'En grupos de tres.', say: 'guet ÍN-tu grups of zríi' },
        { en: 'Two lines on the baseline.', es: 'Dos filas en la línea de fondo.', say: 'tu láins on de BÉIS-lain' },
        { en: 'Grab a ball each.',      es: 'Un balón cada uno.',  say: 'grab a bol íich' },
        { en: 'Spread out.',            es: 'Abríos / separaos.',  say: 'spred áut' },
        { en: 'Line up here.',          es: 'Colocaos aquí.',      say: 'láin op híar' },
      ],
    },
    {
      es: 'Para empezar y marcar el ritmo',
      en: 'Starting & pace',
      items: [
        { en: 'On the whistle.',        es: 'A mi silbato.',       say: 'on de UÍ-sel' },
        { en: 'On my count.',           es: 'A mi cuenta.',        say: 'on mai káunt' },
        { en: 'Three, two, one… go!',   es: 'Tres, dos, uno… ¡ya!', say: 'zríi, tu, uán, góu' },
        { en: 'Full speed.',            es: 'A máxima velocidad.', say: 'ful spíid' },
        { en: 'Half speed.',            es: 'A medio gas.',        say: 'haf spíid' },
        { en: 'Game speed!',            es: '¡A ritmo de partido!', say: 'gueim spíid' },
        { en: 'Hold up - freeze.',      es: 'Parad - quietos.',    say: 'hóuld op, fríis' },
      ],
    },
    {
      es: 'Durante el ejercicio',
      en: 'During the drill',
      items: [
        { en: 'Switch sides.',          es: 'Cambiad de lado.',    say: 'suích sáids' },
        { en: 'Rotate.',                es: 'Rotad.',              say: 'RÓU-teit' },
        { en: 'Next group, go.',        es: 'Siguiente grupo, ya.', say: 'nekst grup góu' },
        { en: 'Run it again.',          es: 'Otra vez.',           say: 'ron it a-GUÉN' },
        { en: 'Match up.',              es: 'Emparejaos.',         say: 'mach op' },
        { en: 'Make it sharp.',         es: 'Hacedlo limpio / preciso.', say: 'méik it sharp' },
        { en: 'No fouls.',              es: 'Sin faltas.',         say: 'nóu fáuls' },
      ],
    },
    {
      es: 'Para cerrar',
      en: 'Wrapping up',
      items: [
        { en: 'Last one.',              es: 'La última.',          say: 'last uán' },
        { en: 'Water break - two minutes.', es: 'A beber - dos minutos.', say: 'UÓ-ter bréik, tu MÍ-nits' },
        { en: 'Good work today.',       es: 'Buen trabajo hoy.',   say: 'gud uork tu-DÉI' },
        { en: 'Bring it in, hands in.', es: 'Piña, manos al centro.', say: 'bring it in, hands in' },
      ],
    },
  ],

  drills: [
    {
      id: 'three-man-weave',
      en: 'Three-man weave',
      es: 'Tres en zigzag (onda)',
      meta: 'Calentamiento · 5–8 min',
      setup: { en: 'Three lines on the baseline. Middle line has the ball.',
               es: 'Tres filas en la línea de fondo. La del medio con balón.' },
      steps: [
        { en: 'Middle player starts with the ball.', es: 'El jugador del medio empieza con balón.' },
        { en: 'Pass, then run behind the player you passed to.', es: 'Pasa y corre por detrás del que recibe.' },
        { en: 'Fill the outside lane, catch, and pass again.', es: 'Ocupa el carril exterior, recibe y vuelve a pasar.' },
        { en: 'Two dribbles maximum - keep it moving.', es: 'Máximo dos botes - mantenedlo fluido.' },
        { en: 'Finish with a layup.', es: 'Terminad con una bandeja.' },
        { en: 'Grab the rebound and bring it back the other way.', es: 'Coged el rebote y volved por el otro lado.' },
      ],
      cues: [
        { en: 'Follow your pass!', es: '¡Sigue tu pase!' },
        { en: 'Sharp passes!', es: '¡Pases precisos!' },
      ],
    },
    {
      id: 'shell-drill',
      en: 'Shell drill (4-on-4)',
      es: 'Defensivo 4x4 (shell)',
      meta: 'Defensa · 10 min',
      setup: { en: 'Four on offense around the perimeter, four on defense matched up.',
               es: 'Cuatro en ataque por el perímetro, cuatro en defensa emparejados.' },
      steps: [
        { en: 'Offense, pass the ball around - no dribble yet.', es: 'Ataque, mover el balón - todavía sin bote.' },
        { en: 'On every pass, defense jumps to the ball.', es: 'En cada pase, la defensa salta hacia el balón.' },
        { en: 'On the ball: pressure. One pass away: deny.', es: 'Al balón: presión. A un pase: negar.' },
        { en: 'Two passes away: drop and help.', es: 'A dos pases: bajar y ayudar.' },
        { en: 'Talk on every screen - call it out.', es: 'Hablad en cada bloqueo - avisad.' },
        { en: 'On the whistle, we go live.', es: 'Al silbato, se juega libre.' },
      ],
      cues: [
        { en: 'Jump to the ball!', es: '¡Salta al balón!' },
        { en: 'Talk to each other!', es: '¡Comunicaos!' },
        { en: 'Close out under control.', es: 'Bascula controlado.' },
      ],
    },
    {
      id: 'closeout-1v1',
      en: 'Closeout 1-on-1',
      es: 'Basculación y 1x1',
      meta: 'Defensa · 8 min',
      setup: { en: 'Defender starts under the rim with the ball. Attacker waits on the wing.',
               es: 'El defensor empieza bajo el aro con balón. El atacante espera en el ala.' },
      steps: [
        { en: 'Defender passes out to the attacker and closes out.', es: 'El defensor pasa al atacante y bascula.' },
        { en: 'Close out high, short steps, hand up.', es: 'Bascula alto, pasos cortos, mano arriba.' },
        { en: 'Attacker reads it: shoot or drive.', es: 'El atacante lee: tira o penetra.' },
        { en: 'Live until a stop or a basket.', es: 'Se juega hasta parada o canasta.' },
        { en: 'Then switch roles.', es: 'Después, cambiad de rol.' },
      ],
      cues: [
        { en: 'Break down - don\'t fly by!', es: '¡Frena - no te pases de largo!' },
        { en: "Contest, don't foul.", es: 'Disputa, sin falta.' },
      ],
    },
    {
      id: 'layup-lines',
      en: 'Layup lines',
      es: 'Filas de bandejas',
      meta: 'Calentamiento · 5 min',
      setup: { en: 'Two lines: one to shoot, one to rebound.',
               es: 'Dos filas: una tira, otra rebotea.' },
      steps: [
        { en: 'Shooting line starts on the wing.', es: 'La fila de tiro empieza en el ala.' },
        { en: 'Drive in and finish with a layup.', es: 'Penetra y termina con bandeja.' },
        { en: 'Rebound line grabs it before it hits the floor.', es: 'La fila de rebote la coge antes de que toque el suelo.' },
        { en: 'Pass out to the next shooter.', es: 'Pasa al siguiente tirador.' },
        { en: 'Then go to the back of the other line.', es: 'Luego, al final de la otra fila.' },
      ],
      cues: [
        { en: 'Use the backboard!', es: '¡Usa el tablero!' },
        { en: 'High off the glass.', es: 'Alto contra el tablero.' },
      ],
    },
    {
      id: 'defensive-slides',
      en: 'Defensive slides',
      es: 'Desplazamientos defensivos',
      meta: 'Físico · 4 min',
      setup: { en: 'Players spread out, low in a defensive stance.',
               es: 'Jugadores repartidos, abajo en posición defensiva.' },
      steps: [
        { en: 'Get low - wide stance, hands up.', es: 'Abajo - postura ancha, manos arriba.' },
        { en: 'Slide on my hand: left, right.', es: 'Deslizaos según mi mano: izquierda, derecha.' },
        { en: "Don't cross your feet.", es: 'No crucéis los pies.' },
        { en: 'Stay on the balls of your feet.', es: 'Sobre la planta de los pies.' },
        { en: 'Thirty seconds - push through it.', es: 'Treinta segundos - apretad.' },
      ],
      cues: [
        { en: 'Lower!', es: '¡Más abajo!' },
        { en: "Don't stand up!", es: '¡No os levantéis!' },
      ],
    },
  ],
};
